#!/bin/bash

set -euo pipefail
. /.functions

set_or_default BASE_DIR "/app"
set_or_default CONF_DIR "${BASE_DIR}/conf"

set_or_default ZOOCFGDIR "${CONF_DIR}"

FQSN="_${DNS_PORT}._tcp.${DNS_SERVICE}.${DNS_NAMESPACE}.svc."

CLUSTER_DOMAIN="$(get_cluster_domain)" || fail "Could not compute the cluster domain"
[ -n "${CLUSTER_DOMAIN}" ] && FQSN+="${CLUSTER_DOMAIN}."

eyes "Fetching the server peer list (${FQSN})"

readarray -t SERVERS < <(dig +short -t SRV "${FQSN}" | sort -k 4)

SERVER_FILE="${CONF_DIR}/zookeeper-servers.cfg.dynamic"
:> "${SERVER_FILE}"
for SERVER in "${SERVERS[@]}" ; do
	read PRIORITY WEIGHT PORT TARGET <<< "${SERVER}"
	IFS="." read BASENAME REST <<< "${TARGET}"
	if [[ "${BASENAME}" =~ ^.*-([0-9]+)$ ]] ; then
		SERVER_ID="$(( ${BASH_REMATCH[1]} + 1 ))"
		SERVER_ID="$(( 10#${SERVER_ID} ))"
		[ ${SERVER_ID} -ge 1 ] && [ ${SERVER_ID} -le 255 ] || fail "The SERVER_ID value must be in the range [1..255] (${SERVER_ID})"
		ok "Found server # ${SERVER_ID} = [${TARGET}]"
		echo "server.${SERVER_ID}=${TARGET}:2888:3888:participant;${PORT}" >> "${SERVER_FILE}"
	else
		err "The server [${SERVER}] is not a valid stateful pod name (must end with a number), ignoring it!"
	fi
done
